### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by eflowbeach** [piensa/d3-metar#1]
https://beta.observablehq.com/@lenninlasd/wind-barbs-svg-library gives: TypeError: Cannot read property 'stations' of undefined

**Comment by ingenieroariel** [comment]
@eflowbeach we kept working on it but never updated old examples - @Lenninlasd can you help us get a version working from unpkg on observable with just open datasets?

**Comment by Lenninlasd** [comment]
It's working now @ingenieroariel @eflowbeach  :)
https://beta.observablehq.com/@lenninlasd/wind-barbs-svg-library
